version: "3.7"

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  app:
    image: chayward1/users
    build: .
    ports:
      - 8081:8080
    depends_on:
      - postgres
